<?php
/**
 * Copyright © 2016 ShopGo. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @see \ShopGo\ShippingCore\Block\Adminhtml\Shipping\Additional\Form
 */
?>
<section class="shopgo-shipping-additional-form admin__page-section" style="display:none;">
    <?php echo /* @escapeNotVerified */ $block->getData('shipping_additional_form_html') ?>
</section>
